GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzY2NTc0NjM5LCJleHAiOjE3NjY1NzQ2Njl9.udCDTuURSRIfu7SAaNsjW0fQ5mNXR79YzjNtlgRHTpw

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzY2NTc0NjM5fQ.495CwIqI8yN9z4cHSwI8WVHsDw2XNRsGMRD1eoI4sEY"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzY2NTc0NjM5fQ.495CwIqI8yN9z4cHSwI8WVHsDw2XNRsGMRD1eoI4sEY"
}


###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}